version: '3.6'

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  pdp_frontend:
    build : 
      context: ./pdp-frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    restart: always
    volumes : 
      - ./pdp-frontend:/app
      - ./pdp-frontend/node_modules:/app/node_modules

  pdp_server:
    build: 
      context: ./pdp_server
      dockerfile: Dockerfile
    ports:
      - 3443:3443
    restart: always      
    volumes:
      - ./pdp_server:/app
      - ./pdp_server/node_modules:/app/node_modules
    networks:
      my_custom_network:
        ipv4_address: 172.18.0.4
  
  fido2_server:
    build: 
      context: ./fido2_server
      dockerfile: Dockerfile
    ports:
      - 5443:5443
    restart: always
    environment:
      - FLASK_ENV=development      
    command: python app.py
    volumes:
      - ./fido2_server:/app
    networks:
      my_custom_network:
        ipv4_address: 172.18.0.5
  
  fido2_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fido2
      MYSQL_USER: fido2_user
      MYSQL_PASSWORD: fido2_password
    volumes:
      - fido2_db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    networks:
      my_custom_network:
        ipv4_address: 172.18.0.3

volumes:
  fido2_db_data:
    driver: local 